CREATE TABLE [dbo].[newapplication] (
    [Id]                    INT          IDENTITY (1, 1) NOT NULL,
    [lastname]              VARCHAR (50) NULL,
    [firstname]             VARCHAR (50) NULL,
    [middlename]            VARCHAR (50) NULL,
    [dob]                   DATE         NULL,
    [gender]                VARCHAR (6)  NULL,
    [martialstatus]         VARCHAR (25) NULL,
    [idtype]                VARCHAR (25) NULL,
    [idnumber]              INT          NULL,
    [phonenumber]           VARCHAR (15) NULL,
    [email]                 VARCHAR (50) NULL,
    [address]               VARCHAR (50) NULL,
    [employername]          VARCHAR (25) NULL,
    [employmentstatus]      VARCHAR (25) NULL,
    [position]              VARCHAR (25) NULL,
    [annualincome]          INT          NULL,
    [yearsemployment]       VARCHAR (10) NULL,
    [employercontact]       VARCHAR (25) NULL,
    [incomeproof]           INT          NULL,
    [identtityproof]        INT          NULL,
    [collateraldocument]    INT          NULL,
    [loantype]              VARCHAR (25) NULL,
    [amount]                INT          NULL,
    [loanpurpose]           VARCHAR (25) NULL,
    [repaymentterm]         VARCHAR (25) NULL,
    [collateraltype]        VARCHAR (25) NULL,
    [estimatedvalue]        INT          NULL,
    [collateraldescription] TEXT         NULL,
    [monthlyincome]         INT          NULL,
    [expenses]              INT          NULL,
    [applicationdate]       DATE   NULL,
    [status]                VARCHAR (50) NULL,
    [assignedofficer]       VARCHAR (50) NULL,
    CONSTRAINT [PK_newapplication] PRIMARY KEY CLUSTERED ([Id] ASC)
);

